### ISSUE TITLE
[Errno 2] No such file or directory: 'all_negatives_geo_with_labels.txt'

### ISSUE THREAD

**Issue by BeifengQAQ** [zeyofu/TARA#3]
I can't get **all_negatives_time_with_labels.txt** and **all_negatives_geo_with_labels.txt** which are used in nyt_dataset.py.

**Comment by zeyofu** [comment]
Could you kindly point me to the line where this file is needed?

**Comment by BeifengQAQ** [comment]
> Could you kindly point me to the line where this file is needed?
The file was read using open(sample_file,'r ') on line 736 of the "nyt_dataset. py" file.

**Comment by zeyofu** [comment]
Sorry for the late reply, it seems that it was created using func def create_all_variations () in the same file on Line 1116

**Comment by beifeng0809** [comment]
> Sorry for the late reply, it seems that it was created using func def create_all_variations () in the same file on Line 1116

But fun def create_ all_ variations() in the same file on Line 1116 used class GeoTemporalDataset and this class calls sample_ from_ full_ negative ('full '), the problem still cannot be solved.

The following figures show the calling relationship.

![image](https://github.com/zeyofu/TARA/assets/157906481/5d624465-373c-4574-ace1-32aa34f6c891)

![image](https://github.com/zeyofu/TARA/assets/157906481/d00069ad-9254-4639-994e-cb7df71b67f1)

![image](https://github.com/zeyofu/TARA/assets/157906481/d23ec4d8-0810-4aa8-b926-ea3f9c69ce29)

**Comment by zeyofu** [comment]
Hi, so sorry for missing these files! Please find them here, and I've added to the Google Drive also. Let me know if there are other problems.

[all_negatives_geo_with_labels.txt](https://github.com/zeyofu/TARA/files/14188439/all_negatives_geo_with_labels.txt)
[all_negatives_time_with_labels.txt](https://github.com/zeyofu/TARA/files/14188440/all_negatives_time_with_labels.txt)

**Comment by beifeng0809** [comment]
> Hi, so sorry for missing these files! Please find them here, and I've added to the Google Drive also. Let me know if there are other problems.
> 
> [all_negatives_geo_with_labels.txt](https://github.com/zeyofu/TARA/files/14188439/all_negatives_geo_with_labels.txt) [all_negatives_time_with_labels.txt](https://github.com/zeyofu/TARA/files/14188440/all_negatives_time_with_labels.txt)

Thanks for your help!
